// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj4o3HK6vAHmoz6v-NEbQGv6nU7u-taL0',
    appId: '1:725084487898:web:ca15854fb374185e2d65e3',
    messagingSenderId: '725084487898',
    projectId: 'crud-57d13',
    authDomain: 'crud-57d13.firebaseapp.com',
    storageBucket: 'crud-57d13.appspot.com',
    measurementId: 'G-3T6Y5PQ6Y0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWXUcBPaIIa4GeqNjZux6fOEmSU63HQ8w',
    appId: '1:725084487898:android:f80ca6b6d7bcfb982d65e3',
    messagingSenderId: '725084487898',
    projectId: 'crud-57d13',
    storageBucket: 'crud-57d13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjNLxJh_rr2CleT6tRkDwdsaLorj3L2bA',
    appId: '1:725084487898:ios:44cb0fee98af727c2d65e3',
    messagingSenderId: '725084487898',
    projectId: 'crud-57d13',
    storageBucket: 'crud-57d13.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjNLxJh_rr2CleT6tRkDwdsaLorj3L2bA',
    appId: '1:725084487898:ios:cd5eaf8ed12b18662d65e3',
    messagingSenderId: '725084487898',
    projectId: 'crud-57d13',
    storageBucket: 'crud-57d13.appspot.com',
    iosBundleId: 'com.example.crud.RunnerTests',
  );
}
